#!/bin/bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

KERNEL_DIR=build/kernel

# some hacking
mkdir -p ${KERNEL_DIR}/debian/stamps


# kernel
pushd ${KERNEL_DIR}
chmod a+x debian/rules
chmod a+x debian/scripts/*
chmod a+x debian/scripts/misc/*
fakeroot debian/rules clean
fakeroot debian/rules binary-headers binary-generic do_zfs=true do_dkms_nvidia=true
popd
