#!/bin/bash
set -xe

source $(dirname $0)/version
cd $(dirname $0)/..

# kernel
mkdir -p build
if [ ! -d build/kernel ]; then
  ${KERNEL_CLONE_CMD} build/kernel
fi
# firmware
if [ ! -d build/firmware ]; then
  ${FIRMWARE_CLONE_CMD} build/firmware
fi
# patches
PATCHES_DIR=$(pwd)/patches
pushd build/kernel
for p in `find ${PATCHES_DIR} -name "*.patch"`; do
    echo "patching $p"
    patch -p1 -i $p
done
popd
